### ISSUE TITLE
Registry entry in installation docs did not match up for me

### ISSUE THREAD

**Issue by jdenicola67** [nycdotnet/TSqlFlex#25]
I have 64-bit Windows and 64-bit SQL Server 2012 installed on my system. The installation doc says:

    * If 32-bit Windows: `HKLM\SOFTWARE\Red Gate\SIPFramework\Plugins`
    * If 64-bit Windows: `HKLM\SOFTWARE\Wow6432Node\Red Gate\SIPFramework\Plugins`

To get it to work, the reg entry on my system was the 32-bit key listed above, even though I am 64/64 on Win and SQL.

On my system, SSMS is installed in Program Files (x86).  I don't think there is a 64-bit version of SSMS. I checked a Windows 2012 64-bit system here and SSMS is also in Program Files (x86) there also.

**Comment by nycdotnet** [comment]
@jdenicola67 I've released Alpha 12 which has a chocolatey package.  Would you be willing to try to test an install from that?  It should pass moderation in just a few days and I'll post the instructions after that.

**Comment by nycdotnet** [comment]
I'm going to close this issue for now.  I've just released beta 1; if this is still an issue in that version (using Chocolatey to install) please let me know and reopen this issue.
