### ISSUE TITLE
Connect to database engine in object explorer hangs SSMS

### ISSUE THREAD

**Issue by tonybater** [nycdotnet/TSqlFlex#33]
If I attempt to connect to another database engine using Object Explorer when a SQL-Flex tab is open then SSMS hangs. I have left this for over an hour and it is still hung.
Workaround is to ensure that any SQL Flex tabs are closed BEFORE attempting to connect to another SQL Instance.

**Comment by nycdotnet** [comment]
Should be fixed in Alpha 11 to be released this evening.  @tonybater , if you still see the issue, please let me know.  Sorry for the long delay.
