### ISSUE TITLE
Can't make it work - SSMS 10.50.2500.0 

### ISSUE THREAD

**Issue by razdyn** [nycdotnet/TSqlFlex#38]
I followed the instructions exactly, but I cannot get the plugin to show up in SSMS.  I put it in 'C:\ProgramData\TsqlFlex', in 'C:\ProgramData\Red Gate\T-SQL Flex', in 'C:\Program Files\Red Gate\TSQL Flex', and in 'C:\Program Files (x86)\Red Gate\TSQL Flex' all with no luck.

Does Alpha 11 not work with SQL Server 2008R2 / SSMS 10.50.2500.0?

Note: Release Alpha 10 works fine.

Here's my environment:
Windows 7 x64 w/SP1 
SQL Server 2008 R2
SSMS - 10.50.2500.0

**Comment by nycdotnet** [comment]
Hi there.  Alpha 11 should work great with that setup - in fact that's what I use at work.  Are you seeing the other items in the button bar that that come with the SIP framework?

Alpha 11 is the first version to have a Chocolatey package - have you ever used that?

https://chocolatey.org/

Once you get Chocolatey installed, the command-line to install T-SQL Flex is:

`choco install tsqlflex -pre`

The Chocolatey installer will also install the SIP framework prerequisite.

**Comment by nycdotnet** [comment]
@razdyn I updated the install docs for Chocolatey.  Please try that and let me know if you can't get it working.

https://github.com/nycdotnet/TSqlFlex/blob/master/InstallationInstructions.md

**Comment by cooxkie** [comment]
Hi,

I have same issue than @razdyn. I tried to install TSQL manually and from chocolatey but T-SQL Flex button does not appear anymore :-(

Here is informations from my SSMS :
 Microsoft SQL Server Management Studio						10.50.1600.1
Microsoft Data Access Components (MDAC)						6.3.9600.17415
Microsoft MSXML						3.0 4.0 6.0 
Microsoft Internet Explorer						9.11.9600.17690
Microsoft .NET Framework						2.0.50727.8009
Operating Sytem						6.3.9600

.net framework installed on my computer is .net 4.5.1 but SSMS says that .net 2.0 is used. Is the issue due to that ?

Regards

**Comment by nycdotnet** [comment]
@cooxkie  - it was working before but isn't now?  Where did you read that SSMS is using .NET 2.0?

**Comment by nycdotnet** [comment]
Oy!  You're right.  I just loaded SSMS 2008 and T-SQL Flex is now not appearing.  I use SSMS 2014 usually.  How annoying!  I will look into this.  So sorry for the trouble.  Thanks for reporting.

**Comment by cooxkie** [comment]
You're welcome ;-) I hope you will find a solution, your plugin will be very usefull for me !

**Comment by nycdotnet** [comment]
Red Gate has indicated that this is a known issue, but is workaround-able.  Apparently their [SQL Scripts](https://github.com/red-gate/sql-scripts) add-in is .NET 4.0 except for the loader that is .NET 3.5 so it works with SSMS 2008.  I'm disappointed that I missed this considering @mauvo took the trouble to explain it to me in detail.

**Comment by cooxkie** [comment]
I'm sorry but I'm not sure to understand what you mean ... is it working on SSMS 2008 or not ;-) ?

**Comment by mauvo** [comment]
@cooxkie It should work if @nycdotnet recompiles for .Net 3.5. Which could be a pain if he's used some new language features or incompatible Nuget packages. An alternative is hosting his application in a separate process using named pipes or maybe MAF. SQL Scripts works this way, but it involved a lot of boilerplate.

Good luck Steve, hopefully the simple fix works... :-)

**Comment by nycdotnet** [comment]
@cooxkie  It doesn't, but I intend to fix it ASAP.  For now, it should work in newer SSMS (like 2012 or higher) which still lets you connect to SQL Server 2008 and earlier databases.  I should have caught this when I initially converted the app.  If I can't get the workaround working, I'll revert to .NET 3.5 and just live with it.

@mauvo Thanks for the reply.  Yeah I specifically did upgrade it to use .NET 4 stuff.  Any chance you'd be willing to indulge my question on the SSMS-addin Google group?

**Comment by cooxkie** [comment]
@mauvo and @nycdotnet : Thanks it's clear now ;-) 
@nycdotnet I'm waiting for your new package (in .net 3.5)
In my side, I will try to install SSMS 2012 but some of my client still to use SSMS 2005 ... so gap will be huge ;-) !

**Comment by nycdotnet** [comment]
I am not actually using any new .NET 4 features (yet), so I should technically be able to downgrade it without much trouble.  I'm in the middle of a big project at the moment so it might be a week or two before I can get to it.

**Comment by cooxkie** [comment]
It's ok, I don't need it for the moment : I have already written my INSERT statement manually ;-) !
but it will be useful for the next time !

**Comment by nycdotnet** [comment]
OK.  In the meantime as @razdyn identified, you can use alpha 10 which is available via the releases page.  https://github.com/nycdotnet/TSqlFlex/releases

**Comment by cooxkie** [comment]
yes, you're right ! it works fine !

**Comment by nycdotnet** [comment]
This should be fixed in beta 1 which I've just released.  Thanks for your patience.
