### ISSUE TITLE
T-SQL CAST(datetime field name AS TIME) thorws an exception when executing To XML Spreadsheet (Excel)

### ISSUE THREAD

**Issue by mfowlergnd** [nycdotnet/TSqlFlex#51]
Here's my query:
SELECT	
	
	,CAST(DATETIME FIELD AS DATE)		CHANGE_DATE
	,CAST(DATETIME FIELD AS TIME)		CHANGE_TIME

FROM table

If I comment out the CAST( ... as TIME) statement, it runs fine.  However, once CAST(...as TIME) is placed back into the code, the following exception:

--Exception encountered while rendering spreadsheet.

/* Specified cast is not valid.

   at TSqlFlex.Core.XmlSpreadsheetRenderer.renderAsXMLSpreadsheet(FlexResultSet resultSet, SqlRunParameters srp)
   at TSqlFlex.Core.QueryWorker.DoSqlQueryWork(DoWorkEventArgs e, BackgroundWorker bw)
*/

**Comment by nycdotnet** [comment]
Thanks for the report.  Sorry for this bug.  I don't know how soon I will get to it as I don't have much time for open source work at the moment.  PRs accepted if you feel comfortable doing that.

**Comment by nycdotnet** [comment]
This should be resolved in T-SQL Flex 0.2.1-beta which I just uploaded to Chocolatey.  Please update and reopen this ticket if it's not fixed.  Thanks for the report.
