### ISSUE TITLE
Does not show up in SSMS v17.9.1

### ISSUE THREAD

**Issue by Dwight1985** [nycdotnet/TSqlFlex#53]

**Comment by Dwight1985** [comment]
Although I followed all instructions both Manual and through Chocolatey, T-SQL Flex does not show up in the menu item. I got it to work on my secondary machine

**Comment by nycdotnet** [comment]
For now it only works on older SSMS as Redgate didn’t update their adapter library.  This is a dup of #49.  Sorry- wish I had time to fix T-SQL Flex up for new SSMS.  PRs definitely accepted.
